name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build gwtcrudapp
        run: |
          cd loaderweb
          ant -noinput -buildfile build.xml          
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()   
        with:
          name: JUnit Tests           
          path: loaderweb/reports/htmlunit.prod/*.xml
          reporter: java-junit